### ISSUE TITLE
Large File and Audio Streaming

### ISSUE THREAD

**Issue by hakan-demirli** [reallyrehan/flask-fileexplorer#10]
Currently, all videos have to be downloaded up to the selected video time to be viewed.
The following stack-overflow question solves this problem:

- https://stackoverflow.com/questions/65366164/how-do-i-stream-large-videos-in-flask

There is also an already implemented solution in the pull requests. But I couldn't verify it since there are path problems.

- https://github.com/reallyrehan/flask-fileexplorer/pull/5

I can also bodge a similar video/audio only code and send a PR.

**Comment by reallyrehan** [comment]
Thanks for the suggestion! Just went over the #5 PR and merged it with main branch after doing a path fix. It couldn't load pages with files that didn't have an extension. Let me know if this is the same issue you noticed?

**Comment by hakan-demirli** [comment]
The video streaming problem seems to be solved. 

In windows it can enter directories with empty files. I can't replicate it.
