### ISSUE TITLE
Ordering files by name

### ISSUE THREAD

**Issue by tensorturtle** [reallyrehan/flask-fileexplorer#11]
Hello @reallyrehan 
First of all, thanks for creating this.
I noticed that the files listed under a given directory are not ordered by name or date. 
Could you point me to where I might be able to add a sorting function?

Thank you
Jason

**Comment by reallyrehan** [comment]
Hey @tensorturtle ,

Thank you - sure that would be a welcome addition, you can have a look at this function,

https://github.com/reallyrehan/flask-fileexplorer/blob/0e03c67af20e67f55888cad476fa6709166cbcbd/setup.py#L189

**Comment by reallyrehan** [comment]
Added functionality for this today in [PR#20](https://github.com/reallyrehan/flask-fileexplorer/pull/20)!
