### ISSUE TITLE
Option to make filename fully visible

### ISSUE THREAD

**Issue by theotherguy2175** [reallyrehan/flask-fileexplorer#18]
If the file name is looks like over 15+ characters it cuts off the rest of the name. Is there any way to have a column size adjuster, or at least have priority to the file name? At least for something like 50+ characters?

**Comment by reallyrehan** [comment]
Hey, have added the functionality to see full filename as tooltip when you hover over the text.
<img width="351" alt="image" src="https://github.com/reallyrehan/flask-fileexplorer/assets/33403815/c22e025f-1a98-4b7c-9e42-c841489a6025">

Will look into making into configurable!

**Comment by reallyrehan** [comment]
Also just added support today for configuring filename length through the config.json file in [PR#20](https://github.com/reallyrehan/flask-fileexplorer/pull/20)
