### ISSUE TITLE
perhaps add requirements file!

### ISSUE THREAD

**Issue by efenfauzi** [reallyrehan/flask-fileexplorer#2]
I trying to run `python3 nosession-setup.py` and got error 
 **jinja2.exceptions.UndefinedError: 'fontawesome_html'** is undefined in `layout.html` 

I look for this error msg, need to install flask_fontawesome. 
Please add requirements file and some other guidelines.

Kinda you forgot to add 
```
from flask_fontawesome import FontAwesome
app = Flask(__name__)
FontAwesome(app)
```
on `nosession-setup.py`

**Comment by intel-maxmurphy** [comment]
I agree this would be very helpful.

**Comment by reallyrehan** [comment]
Thanks for the suggestion @efenfauzi - finally got around to working on this tool an year later and I have added the requirements.txt file.
