### ISSUE TITLE
Unable to clone the repo

### ISSUE THREAD

**Issue by ati07** [reallyrehan/flask-fileexplorer#27]
I get the issue while cloning the repo

Cloning into 'flask-fileexplorer'...
remote: Enumerating objects: 461, done.
remote: Counting objects: 100% (88/88), done.
remote: Compressing objects: 100% (44/44), done.
error: 4228 bytes of body are still expected | 305.00 KiB/s 
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

Please fix this....
Thank you

**Comment by reallyrehan** [comment]
Hi @ati07 , the error you are encountering (“fetch-pack: unexpected disconnect while reading sideband packet” and “fatal: early EOF”) is usually related to network issues or an incomplete download during the clone process. 

Did you try cloning it again?
