### ISSUE TITLE
Is locking to one directory a thing?

### ISSUE THREAD

**Issue by GreenDiscord** [reallyrehan/flask-fileexplorer#3]
I would love to use this for my home network, to share files with my family.

I just would want people to see one directory

Is this possible?

**Comment by reallyrehan** [comment]
Hey, it was initially supported but broke when I added mac support. Just fixed it and it now works for both Mac and Windows.

To lock to one directory, add the directory path for "rootDir" in **config.json** file! It will restrict explorer to only files and folders in that particular directory and will throw an error if you try to access any file/folder outside it.

Format for Mac,
`Users/rehanahmed/Downloads`

Format for Windows,
`C:/Users/Administrator/Documents`
